mqtt:
  broker_url: "mqtt-broker"
  port: 1883
  publish_topic: "plant/sensor"
  subscribe_topic: "plant/commands"
  command_topic: "plant/command"
  data_format: "json"

# InfluxDB configuration
influxdb:
  url: "http://influxdb:8086"
  org: "smart_plant_care"
  bucket: "sensor_data"
  retention_policy: "30d"  # Keep data for 30 days

# Data aggregation settings
aggregation:
  default_window: "1h"
  available_windows: ["1h", "1d", "7d", "30d"]
  max_query_limit: 10000 