services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./configs/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

  # PostgreSQL for relational data (users, plants, devices)
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: smart_plant_care
      POSTGRES_USER: plant_user
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # InfluxDB for time-series sensor data
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=smart_plant_care
      - DOCKER_INFLUXDB_INIT_BUCKET=sensor_data
    volumes:
      - influxdb_data:/var/lib/influxdb2
    restart: unless-stopped

  sensor-service:
    build:
      context: ./services/sensor-service
      dockerfile: Dockerfile
    container_name: sensor-service
    volumes:
      - ./services/sensor-service/config.yaml:/app/config.yaml:ro
    environment:
      - CONFIG_PATH=/app/config.yaml
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=password123
      - INFLUXDB_ORG=smart_plant_care
      - INFLUXDB_BUCKET=sensor_data
    restart: unless-stopped
    depends_on:
      - mqtt-broker
      - influxdb
    ports:
      - "5002:5002"

  analytics-service:
    build:
      context: .
      dockerfile: ./services/analytics-service/Dockerfile
    container_name: analytics-service
    ports:
      - "5003:5000"
    volumes:
      - ./services/analytics-service/config.yaml:/app/config.yaml:ro
    environment:
      - CONFIG_PATH=/app/config.yaml
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=password123
      - INFLUXDB_ORG=smart_plant_care
      - INFLUXDB_BUCKET=sensor_data
      - POSTGRES_URL=postgresql://plant_user:password123@postgres:5432/smart_plant_care
    restart: unless-stopped
    depends_on:
      - mqtt-broker
      - influxdb
      - postgres

  catalogue-service:
    build:
      context: .
      dockerfile: ./services/catalogue-service/Dockerfile
    container_name: catalogue-service
    ports:
      - "5000:5000"
    volumes:
      - ./services/catalogue-service/config.yaml:/app/config.yaml:ro
    environment:
      - CONFIG_PATH=/app/config.yaml
      - POSTGRES_URL=postgresql://plant_user:password123@postgres:5432/smart_plant_care
    restart: unless-stopped
    depends_on:
      - database-init

  cloud-adapter-service:
    build:
      context: ./services/cloud-adapter-service
      dockerfile: Dockerfile
    container_name: cloud-adapter-service
    ports:
      - "5001:5001"
    volumes:
      - ./services/cloud-adapter-service/config.yaml:/app/config.yaml:ro
    environment:
      - CONFIG_PATH=/app/config.yaml
      - SENSOR_DATA_SERVICE_URL=http://sensor-data-service:5004
    restart: unless-stopped
    depends_on:
      - sensor-data-service

  database-init:
    build:
      context: .
      dockerfile: ./services/database-init/Dockerfile
    container_name: database-init
    environment:
      - POSTGRES_URL=postgresql://plant_user:password123@postgres:5432/smart_plant_care
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=password123
      - INFLUXDB_ORG=smart_plant_care
      - INFLUXDB_BUCKET=sensor_data
    restart: "no"
    depends_on:
      - postgres
      - influxdb

  sensor-data-service:
    build:
      context: .
      dockerfile: ./services/sensor-data-service/Dockerfile
    container_name: sensor-data-service
    volumes:
      - ./services/sensor-data-service/config.yaml:/app/config.yaml:ro
    environment:
      - CONFIG_PATH=/app/config.yaml
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=password123
      - INFLUXDB_ORG=smart_plant_care
      - INFLUXDB_BUCKET=sensor_data
      - CATALOGUE_URL=http://catalogue-service:5000
      - POSTGRES_URL=postgresql://plant_user:password123@postgres:5432/smart_plant_care
    restart: unless-stopped
    depends_on:
      - database-init
      - mqtt-broker
      - influxdb
      - catalogue-service
    ports:
      - "5004:5004"

  user-service:
    build:
      context: .
      dockerfile: ./services/user-service/Dockerfile
    container_name: user-service
    volumes:
      - ./services/user-service/config.yaml:/app/config.yaml:ro
    environment:
      - CONFIG_PATH=/app/config.yaml
      - POSTGRES_URL=postgresql://plant_user:password123@postgres:5432/smart_plant_care
      - REST_API_URL=http://sensor-data-service:5004/data
      - SENSOR_API_URL=http://sensor-service:5002/actuator
      - CATALOGUE_API_URL=http://catalogue-service:5000
      - SENSOR_DATA_API_URL=http://sensor-data-service:5004
    restart: unless-stopped
    depends_on:
      - database-init
      - sensor-service
      - sensor-data-service
      - catalogue-service
    ports:
      - "5500:5500"

  nodered:
    image: nodered/node-red:3.1
    container_name: nodered
    ports:
      - "1880:1880"
    volumes:
      - nodered_data:/data
    restart: unless-stopped
    depends_on:
      - mqtt-broker

volumes:
  nodered_data:
  postgres_data:
  influxdb_data: 