mqtt:
  broker_url: "mqtt-broker"
  port: 1883
  publish_topic: "plant/sensor"
  subscribe_topic: "plant/commands"
  command_topic: "plant/command"  # Actuator control (manual, Telegram, automated)
  data_format: "json"

sensor_thresholds:
  temperature:
    min: 15  # Celsius
    max: 35
  humidity:
    min: 30  # Percent
    max: 80
  soil_moisture:
    min: 300  # ADC value or percentage
    max: 800

simulation:
  enabled: true  # Set to true to use simulated sensors
