mqtt:
  broker_url: "mqtt-broker"
  port: 1883
  publish_topic: "plant/sensor"
  subscribe_topic: "plant/assignments"
  command_topic: "plant/command"  # Actuator control (manual, Telegram, automated)
  data_format: "json"

telegram:
  bot_token: "7105387626:AAHyiexS3gA5XPhkox16NfVRq9hAx8FxcA8"
