name: Build all Docker services

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build all services with Docker Compose
        run: docker compose -f docker-compose.yml build
